//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI2.SearchAddress {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.address.lands.nsw.gov", ConfigurationName="SearchAddress.AddressSearch")]
    public interface AddressSearch {
        
        // CODEGEN: Parameter 'findAddressByPlanReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="findAddressByPlan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="findAddressByPlanReturn")]
        WebUI2.SearchAddress.findAddressByPlanResponse findAddressByPlan(WebUI2.SearchAddress.findAddressByPlanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="findAddressByPlan", ReplyAction="*")]
        System.Threading.Tasks.Task<WebUI2.SearchAddress.findAddressByPlanResponse> findAddressByPlanAsync(WebUI2.SearchAddress.findAddressByPlanRequest request);
        
        // CODEGEN: Parameter 'findAddressReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="findAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="findAddressReturn")]
        WebUI2.SearchAddress.findAddressResponse findAddress(WebUI2.SearchAddress.findAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="findAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<WebUI2.SearchAddress.findAddressResponse> findAddressAsync(WebUI2.SearchAddress.findAddressRequest request);
        
        // CODEGEN: Parameter 'findAddressByPlanCadIdReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="findAddressByPlanCadId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="findAddressByPlanCadIdReturn")]
        WebUI2.SearchAddress.findAddressByPlanCadIdResponse findAddressByPlanCadId(WebUI2.SearchAddress.findAddressByPlanCadIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="findAddressByPlanCadId", ReplyAction="*")]
        System.Threading.Tasks.Task<WebUI2.SearchAddress.findAddressByPlanCadIdResponse> findAddressByPlanCadIdAsync(WebUI2.SearchAddress.findAddressByPlanCadIdRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.address.lands.nsw.gov")]
    public partial class LotAddressResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LotAddressRecord[] addressesField;
        
        private string errMsgField;
        
        private int numRecsField;
        
        private SearchMethod searchMethodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LotAddressRecord[] addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
                this.RaisePropertyChanged("addresses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string errMsg {
            get {
                return this.errMsgField;
            }
            set {
                this.errMsgField = value;
                this.RaisePropertyChanged("errMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numRecs {
            get {
                return this.numRecsField;
            }
            set {
                this.numRecsField = value;
                this.RaisePropertyChanged("numRecs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public SearchMethod searchMethod {
            get {
                return this.searchMethodField;
            }
            set {
                this.searchMethodField = value;
                this.RaisePropertyChanged("searchMethod");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.address.lands.nsw.gov")]
    public partial class LotAddressRecord : AddressRecord {
        
        private string lotNumberField;
        
        private System.Nullable<int> planNumberField;
        
        private string planTypeField;
        
        private string sectionNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string lotNumber {
            get {
                return this.lotNumberField;
            }
            set {
                this.lotNumberField = value;
                this.RaisePropertyChanged("lotNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<int> planNumber {
            get {
                return this.planNumberField;
            }
            set {
                this.planNumberField = value;
                this.RaisePropertyChanged("planNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string planType {
            get {
                return this.planTypeField;
            }
            set {
                this.planTypeField = value;
                this.RaisePropertyChanged("planType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string sectionNumber {
            get {
                return this.sectionNumberField;
            }
            set {
                this.sectionNumberField = value;
                this.RaisePropertyChanged("sectionNumber");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LotAddressRecord))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.address.lands.nsw.gov")]
    public partial class AddressRecord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int houseNumberFirstField;
        
        private string houseNumberFirstSuffixField;
        
        private int houseNumberSecondField;
        
        private string houseNumberSecondSuffixField;
        
        private long objectIdField;
        
        private long postCodeField;
        
        private string roadNameField;
        
        private string roadSuffixField;
        
        private string roadTypeField;
        
        private string shortAddressStringField;
        
        private string suburbNameField;
        
        private string addressTypeField;
        
        private string councilField;
        
        private string houseNumberStringField;
        
        private AddressPoint addressPointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int houseNumberFirst {
            get {
                return this.houseNumberFirstField;
            }
            set {
                this.houseNumberFirstField = value;
                this.RaisePropertyChanged("houseNumberFirst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string houseNumberFirstSuffix {
            get {
                return this.houseNumberFirstSuffixField;
            }
            set {
                this.houseNumberFirstSuffixField = value;
                this.RaisePropertyChanged("houseNumberFirstSuffix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int houseNumberSecond {
            get {
                return this.houseNumberSecondField;
            }
            set {
                this.houseNumberSecondField = value;
                this.RaisePropertyChanged("houseNumberSecond");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string houseNumberSecondSuffix {
            get {
                return this.houseNumberSecondSuffixField;
            }
            set {
                this.houseNumberSecondSuffixField = value;
                this.RaisePropertyChanged("houseNumberSecondSuffix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long objectId {
            get {
                return this.objectIdField;
            }
            set {
                this.objectIdField = value;
                this.RaisePropertyChanged("objectId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long postCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
                this.RaisePropertyChanged("postCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string roadName {
            get {
                return this.roadNameField;
            }
            set {
                this.roadNameField = value;
                this.RaisePropertyChanged("roadName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string roadSuffix {
            get {
                return this.roadSuffixField;
            }
            set {
                this.roadSuffixField = value;
                this.RaisePropertyChanged("roadSuffix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string roadType {
            get {
                return this.roadTypeField;
            }
            set {
                this.roadTypeField = value;
                this.RaisePropertyChanged("roadType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string shortAddressString {
            get {
                return this.shortAddressStringField;
            }
            set {
                this.shortAddressStringField = value;
                this.RaisePropertyChanged("shortAddressString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string suburbName {
            get {
                return this.suburbNameField;
            }
            set {
                this.suburbNameField = value;
                this.RaisePropertyChanged("suburbName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string addressType {
            get {
                return this.addressTypeField;
            }
            set {
                this.addressTypeField = value;
                this.RaisePropertyChanged("addressType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string council {
            get {
                return this.councilField;
            }
            set {
                this.councilField = value;
                this.RaisePropertyChanged("council");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string houseNumberString {
            get {
                return this.houseNumberStringField;
            }
            set {
                this.houseNumberStringField = value;
                this.RaisePropertyChanged("houseNumberString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public AddressPoint addressPoint {
            get {
                return this.addressPointField;
            }
            set {
                this.addressPointField = value;
                this.RaisePropertyChanged("addressPoint");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.address.lands.nsw.gov")]
    public partial class AddressPoint : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string coordRefSysField;
        
        private double centreXField;
        
        private double centreYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string coordRefSys {
            get {
                return this.coordRefSysField;
            }
            set {
                this.coordRefSysField = value;
                this.RaisePropertyChanged("coordRefSys");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double centreX {
            get {
                return this.centreXField;
            }
            set {
                this.centreXField = value;
                this.RaisePropertyChanged("centreX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double centreY {
            get {
                return this.centreYField;
            }
            set {
                this.centreYField = value;
                this.RaisePropertyChanged("centreY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://data.address.lands.nsw.gov")]
    public partial class AddressResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AddressRecord[] addressesField;
        
        private string errMsgField;
        
        private int numRecsField;
        
        private SearchMethod searchMethodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AddressRecord[] addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
                this.RaisePropertyChanged("addresses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string errMsg {
            get {
                return this.errMsgField;
            }
            set {
                this.errMsgField = value;
                this.RaisePropertyChanged("errMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numRecs {
            get {
                return this.numRecsField;
            }
            set {
                this.numRecsField = value;
                this.RaisePropertyChanged("numRecs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public SearchMethod searchMethod {
            get {
                return this.searchMethodField;
            }
            set {
                this.searchMethodField = value;
                this.RaisePropertyChanged("searchMethod");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://utl.search.address.lands.nsw.gov")]
    public partial class SearchMethod : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] methodDescriptionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] methodDescriptions {
            get {
                return this.methodDescriptionsField;
            }
            set {
                this.methodDescriptionsField = value;
                this.RaisePropertyChanged("methodDescriptions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAddressByPlan", WrapperNamespace="http://ws.address.lands.nsw.gov", IsWrapped=true)]
    public partial class findAddressByPlanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.address.lands.nsw.gov", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string planType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.address.lands.nsw.gov", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string lotNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.address.lands.nsw.gov", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string sectionNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.address.lands.nsw.gov", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int> planNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.address.lands.nsw.gov", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string projection;
        
        public findAddressByPlanRequest() {
        }
        
        public findAddressByPlanRequest(string planType, string lotNumber, string sectionNumber, System.Nullable<int> planNumber, string projection) {
            this.planType = planType;
            this.lotNumber = lotNumber;
            this.sectionNumber = sectionNumber;
            this.planNumber = planNumber;
            this.projection = projection;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAddressByPlanResponse", WrapperNamespace="http://ws.address.lands.nsw.gov", IsWrapped=true)]
    public partial class findAddressByPlanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.address.lands.nsw.gov", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public WebUI2.SearchAddress.LotAddressResult findAddressByPlanReturn;
        
        public findAddressByPlanResponse() {
        }
        
        public findAddressByPlanResponse(WebUI2.SearchAddress.LotAddressResult findAddressByPlanReturn) {
            this.findAddressByPlanReturn = findAddressByPlanReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAddress", WrapperNamespace="http://ws.address.lands.nsw.gov", IsWrapped=true)]
    public partial class findAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.address.lands.nsw.gov", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string houseNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.address.lands.nsw.gov", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string roadName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.address.lands.nsw.gov", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string roadType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.address.lands.nsw.gov", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string suburb;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.address.lands.nsw.gov", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string postCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.address.lands.nsw.gov", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string projection;
        
        public findAddressRequest() {
        }
        
        public findAddressRequest(string houseNumber, string roadName, string roadType, string suburb, string postCode, string projection) {
            this.houseNumber = houseNumber;
            this.roadName = roadName;
            this.roadType = roadType;
            this.suburb = suburb;
            this.postCode = postCode;
            this.projection = projection;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAddressResponse", WrapperNamespace="http://ws.address.lands.nsw.gov", IsWrapped=true)]
    public partial class findAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.address.lands.nsw.gov", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public WebUI2.SearchAddress.AddressResult findAddressReturn;
        
        public findAddressResponse() {
        }
        
        public findAddressResponse(WebUI2.SearchAddress.AddressResult findAddressReturn) {
            this.findAddressReturn = findAddressReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAddressByPlanCadId", WrapperNamespace="http://ws.address.lands.nsw.gov", IsWrapped=true)]
    public partial class findAddressByPlanCadIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.address.lands.nsw.gov", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<long> cadid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.address.lands.nsw.gov", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string projection;
        
        public findAddressByPlanCadIdRequest() {
        }
        
        public findAddressByPlanCadIdRequest(System.Nullable<long> cadid, string projection) {
            this.cadid = cadid;
            this.projection = projection;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAddressByPlanCadIdResponse", WrapperNamespace="http://ws.address.lands.nsw.gov", IsWrapped=true)]
    public partial class findAddressByPlanCadIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.address.lands.nsw.gov", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public WebUI2.SearchAddress.LotAddressResult findAddressByPlanCadIdReturn;
        
        public findAddressByPlanCadIdResponse() {
        }
        
        public findAddressByPlanCadIdResponse(WebUI2.SearchAddress.LotAddressResult findAddressByPlanCadIdReturn) {
            this.findAddressByPlanCadIdReturn = findAddressByPlanCadIdReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddressSearchChannel : WebUI2.SearchAddress.AddressSearch, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddressSearchClient : System.ServiceModel.ClientBase<WebUI2.SearchAddress.AddressSearch>, WebUI2.SearchAddress.AddressSearch {
        
        public AddressSearchClient() {
        }
        
        public AddressSearchClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddressSearchClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressSearchClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressSearchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebUI2.SearchAddress.findAddressByPlanResponse WebUI2.SearchAddress.AddressSearch.findAddressByPlan(WebUI2.SearchAddress.findAddressByPlanRequest request) {
            return base.Channel.findAddressByPlan(request);
        }
        
        public WebUI2.SearchAddress.LotAddressResult findAddressByPlan(string planType, string lotNumber, string sectionNumber, System.Nullable<int> planNumber, string projection) {
            WebUI2.SearchAddress.findAddressByPlanRequest inValue = new WebUI2.SearchAddress.findAddressByPlanRequest();
            inValue.planType = planType;
            inValue.lotNumber = lotNumber;
            inValue.sectionNumber = sectionNumber;
            inValue.planNumber = planNumber;
            inValue.projection = projection;
            WebUI2.SearchAddress.findAddressByPlanResponse retVal = ((WebUI2.SearchAddress.AddressSearch)(this)).findAddressByPlan(inValue);
            return retVal.findAddressByPlanReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebUI2.SearchAddress.findAddressByPlanResponse> WebUI2.SearchAddress.AddressSearch.findAddressByPlanAsync(WebUI2.SearchAddress.findAddressByPlanRequest request) {
            return base.Channel.findAddressByPlanAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebUI2.SearchAddress.findAddressByPlanResponse> findAddressByPlanAsync(string planType, string lotNumber, string sectionNumber, System.Nullable<int> planNumber, string projection) {
            WebUI2.SearchAddress.findAddressByPlanRequest inValue = new WebUI2.SearchAddress.findAddressByPlanRequest();
            inValue.planType = planType;
            inValue.lotNumber = lotNumber;
            inValue.sectionNumber = sectionNumber;
            inValue.planNumber = planNumber;
            inValue.projection = projection;
            return ((WebUI2.SearchAddress.AddressSearch)(this)).findAddressByPlanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebUI2.SearchAddress.findAddressResponse WebUI2.SearchAddress.AddressSearch.findAddress(WebUI2.SearchAddress.findAddressRequest request) {
            return base.Channel.findAddress(request);
        }
        
        public WebUI2.SearchAddress.AddressResult findAddress(string houseNumber, string roadName, string roadType, string suburb, string postCode, string projection) {
            WebUI2.SearchAddress.findAddressRequest inValue = new WebUI2.SearchAddress.findAddressRequest();
            inValue.houseNumber = houseNumber;
            inValue.roadName = roadName;
            inValue.roadType = roadType;
            inValue.suburb = suburb;
            inValue.postCode = postCode;
            inValue.projection = projection;
            WebUI2.SearchAddress.findAddressResponse retVal = ((WebUI2.SearchAddress.AddressSearch)(this)).findAddress(inValue);
            return retVal.findAddressReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebUI2.SearchAddress.findAddressResponse> WebUI2.SearchAddress.AddressSearch.findAddressAsync(WebUI2.SearchAddress.findAddressRequest request) {
            return base.Channel.findAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebUI2.SearchAddress.findAddressResponse> findAddressAsync(string houseNumber, string roadName, string roadType, string suburb, string postCode, string projection) {
            WebUI2.SearchAddress.findAddressRequest inValue = new WebUI2.SearchAddress.findAddressRequest();
            inValue.houseNumber = houseNumber;
            inValue.roadName = roadName;
            inValue.roadType = roadType;
            inValue.suburb = suburb;
            inValue.postCode = postCode;
            inValue.projection = projection;
            return ((WebUI2.SearchAddress.AddressSearch)(this)).findAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebUI2.SearchAddress.findAddressByPlanCadIdResponse WebUI2.SearchAddress.AddressSearch.findAddressByPlanCadId(WebUI2.SearchAddress.findAddressByPlanCadIdRequest request) {
            return base.Channel.findAddressByPlanCadId(request);
        }
        
        public WebUI2.SearchAddress.LotAddressResult findAddressByPlanCadId(System.Nullable<long> cadid, string projection) {
            WebUI2.SearchAddress.findAddressByPlanCadIdRequest inValue = new WebUI2.SearchAddress.findAddressByPlanCadIdRequest();
            inValue.cadid = cadid;
            inValue.projection = projection;
            WebUI2.SearchAddress.findAddressByPlanCadIdResponse retVal = ((WebUI2.SearchAddress.AddressSearch)(this)).findAddressByPlanCadId(inValue);
            return retVal.findAddressByPlanCadIdReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebUI2.SearchAddress.findAddressByPlanCadIdResponse> WebUI2.SearchAddress.AddressSearch.findAddressByPlanCadIdAsync(WebUI2.SearchAddress.findAddressByPlanCadIdRequest request) {
            return base.Channel.findAddressByPlanCadIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebUI2.SearchAddress.findAddressByPlanCadIdResponse> findAddressByPlanCadIdAsync(System.Nullable<long> cadid, string projection) {
            WebUI2.SearchAddress.findAddressByPlanCadIdRequest inValue = new WebUI2.SearchAddress.findAddressByPlanCadIdRequest();
            inValue.cadid = cadid;
            inValue.projection = projection;
            return ((WebUI2.SearchAddress.AddressSearch)(this)).findAddressByPlanCadIdAsync(inValue);
        }
    }
}
