//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderedProduct
    {
        public int RecordId { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string Category { get; set; }
        public string LongDescription { get; set; }
        public string ExternalLink { get; set; }
        public string SubCategory { get; set; }
        public Nullable<int> NordStromId { get; set; }
        public string SelectedSize { get; set; }
        public string SelectedColor { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
