//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderedProducts = new HashSet<OrderedProduct>();
        }
    
        public int Id { get; set; }
        public string RequestTxnId { get; set; }
        public string RequestFirstName { get; set; }
        public string RequestLastName { get; set; }
        public string Total { get; set; }
        public string RequestPaymentDate { get; set; }
        public string CspShippingAddress { get; set; }
        public string RequestListOfProducts { get; set; }
        public string CartNumberOfItems { get; set; }
        public string CspPayerEmail { get; set; }
        public string CspContactNumber { get; set; }
        public string RequestNotes { get; set; }
        public string RequestPendingReason { get; set; }
        public string RequestPayerId { get; set; }
        public string RequestReceiverId { get; set; }
        public string RequestPaymentStatus { get; set; }
        public string RequestPaymentType { get; set; }
        public string RequestCurrency { get; set; }
        public string RequestResidenceCnt { get; set; }
        public string RequestTxnType { get; set; }
        public string PayPalPayerId { get; set; }
        public string ShiptoName { get; set; }
        public string ShippingCost { get; set; }
        public string SubTotal { get; set; }
    
        public virtual ICollection<OrderedProduct> OrderedProducts { get; set; }
    }
}
