//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductToColors = new HashSet<ProductToColor>();
            this.ProductToSizes = new HashSet<ProductToSize>();
        }
    
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string Category { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageMimeType { get; set; }
        public string LongDescription { get; set; }
        public string ExternalLink { get; set; }
        public string SubCategory { get; set; }
        public Nullable<int> NordstromId { get; set; }
        public string SelectedSize { get; set; }
        public string SelectedColour { get; set; }
    
        public virtual ICollection<ProductToColor> ProductToColors { get; set; }
        public virtual ICollection<ProductToSize> ProductToSizes { get; set; }
    }
}
